# basic colors
text_composition_strategy platform
foreground            #ffffff
background            #0c0c0d
selection_foreground  #ffffff
selection_background  #4b4b4b

# Cursor colors
cursor            #ffffff
cursor_text_color background

# URL
url_color #56b6c2

# Tab bar colors
active_tab_foreground   #0c0c0d
active_tab_background   #ffffff
inactive_tab_foreground #ffffff
inactive_tab_background #2d2d2d

# black
color0  #3c3c3c
color8  #454545

# red
color1  #e08c75
color9  #e08c75

# green
color2  #98c379
color10 #98c379

# yellow
color3  #e5c07b
color11 #e5c07b

# blue
color4  #61afef
color12 #61afef

# magenta
color5  #c678dd
color13 #c678dd

# cyan
color6  #56b6c2
color14 #56b6c2

# white
color7  #d0d0d0
color15 #ffffff
