# basic colors
text_composition_strategy 1.7 30
foreground            #1a1a1a
background            #f5f5f5
selection_foreground  #1a1a1a
selection_background  #b9b9b9

# Cursor colors
cursor            #1a1a1a
cursor_text_color background

# URL
url_color #1f8999

# Tab bar colors
active_tab_foreground   #f5f5f5
active_tab_background   #1a1a1a
inactive_tab_foreground #1a1a1a
inactive_tab_background #d7d7d7

# black
color0  #555555
color8  #666666

# red
color1  #a32412
color9  #a32412

# green
color2  #2c5c16
color10 #2c5c16

# yellow
color3  #8a680b
color11 #8a680b

# blue
color4  #154ba3
color12 #154ba3

# magenta
color5  #68258f
color13 #68258f

# cyan
color6  #126473
color14 #126473

# white
color7  #333333
color15 #1a1a1a
