-- require("modules.envs")
require("modules.monitors")
require("modules.autostart")
require("modules.appearance")
require("modules.layout")
require("modules.input")
require("modules.misc")
require("modules.windowrules")
require("modules.keybindings")
-- require("modules.permission")
